version: '2'

services:
  db:
    image: oscarfonts/h2:1.4.197
    container_name: zeebe_db
    ports:
      - "1521:1521"
      - "81:81"
    networks:
        - zeebe-network
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.16.3
    environment:
        - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
    volumes:
      - ./zeebe/zeebe-simple-monitor-exporter.jar:/usr/local/zeebe/lib/zeebe-simple-monitor-exporter.jar
      - ./zeebe/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml 
    networks:
        - zeebe-network
    depends_on:
        - db
  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:0.12.0
    environment:
      - spring.datasource.url=jdbc:h2:tcp://db:1521/zeebe-monitor
      - io.zeebe.monitor.connectionString=zeebe:26500
    ports:
      - "8081:8080"
    depends_on:
        - db
    networks:
        - zeebe-network

  fnserver:
    container_name: fnserver
    image: artunsubasi/fnserver-zeebe:0.1.9
    environment:
      - FN_LOG_LEVEL=INFO
      - FN_LB_URL=http://localhost:8080
      - FN_API_SERVER_URL=http://localhost:8080
      - FN_ZEEBE_GATEWAY_URL=zeebe:26500
      - FN_IOFS_DOCKER_PATH=$PWD/iofs
      - FN_IOFS_PATH=/iofs
      - FDK_DEBUG=1
    volumes:
      - ./fn-data:/app/data
      - ./iofs:/iofs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    depends_on:
      - zeebe
    networks:
      - zeebe-network

networks:
    zeebe-network:
      driver: bridge
